version: '3.8'

services:
  # Frontend development server (for development)
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - skypad-network

  # Backend API server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app/backend
      - ./.env:/app/.env:ro
      - ./sage-striker-294302-b248a695e8e5.json:/app/google-credentials.json:ro
    environment:
      - PORT=8080
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json
    env_file:
      - .env
    networks:
      - skypad-network

  # Production build (frontend + backend combined)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
      - ./sage-striker-294302-b248a695e8e5.json:/app/google-credentials.json:ro
    networks:
      - skypad-network
    profiles:
      - production

networks:
  skypad-network:
    driver: bridge
